flowchart TB
  %% Ambientes
  subgraph Accounts [AWS Accounts]
    direction TB
    Prod[Production]
    Staging[Staging]
    Shared[Shared Services]
  end

  %% Camada Pública
  subgraph PublicLayer [Public Layer]
    User
    ALB[ALB (Load Balancer)]
  end

  %% VPC e Sub-redes
  subgraph VPC [VPC]
    direction TB
    subgraph PublicSubnet [Public Subnet]
      ALB
    end
    subgraph PrivateSubnet [Private Subnet]
      EKS
      NodeX86[x86 NodeGroup]
      NodeARM[ARM NodeGroup]
      Karpenter
      subgraph Workloads
        FE[Frontend (React SPA)]
        BE[Backend (Flask API)]
      end
    end
    subgraph IsolatedSubnet [Isolated Subnet]
      RDS
    end
  end

  %% Camada de Dados
  subgraph DataLayer [Data & Security]
    S3
    ECR
    Secrets
  end

  %% CI/CD e Observabilidade
  subgraph CICD_Observability [CI/CD & Observability]
    CI
    Datadog
  end

  %% Fluxos
  User --> ALB
  ALB --> FE
  FE --> BE
  FE -.-> EKS
  BE -.-> EKS
  EKS --> NodeX86
  EKS --> NodeARM
  NodeX86 -.-> Karpenter
  NodeARM -.-> Karpenter
  BE --> RDS
  BE --> S3
  EKS --> ECR
  EKS --> Secrets
  CI --> ECR
  CI --> EKS
  RDS -->|Backups| S3
  EKS --> Datadog
  NodeX86 --> Datadog
  NodeARM --> Datadog
  FE -.-> Datadog
  BE -.-> Datadog
  %% Ambientes controlam VPCs
  Prod --> VPC
  Staging --> VPC
  Shared --> CICD_Observability
